# Generated by Django 5.0.4 on 2024-07-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrocompleto_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='Endereço padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_formatado',
            field=models.CharField(default='Endereço não formatado', max_length=255),
        ),
    ]
